### ISSUE TITLE
2.11.0: Planets dissapeared?

### ISSUE THREAD

**Issue by LordMike** [Touhma/DSP_Galactic_Scale#203]
Hi,

I'm just trying out GS, and this morning I updated to 2.11.0, as I was _just_ about to land on a different planet. I noticed it was missing, as I kept missing it and cruise assist was pointing me far away from the supposed planet.. Checked the changelog, and 2.11.0 specifically touches on this.

I reverted to 2.10.3, and I can now see/land on the planet I picked out.

I'm running a bunch of other mods too, but I'm guessing they won't affect this type of stuff.. :)

Mike.

**Comment by innominata** [comment]
Yes unfortunately 2.11.0 had a typo that broke existing saves, hopefully 2.11.1 / 2.11.2 fixes it

**Comment by LordMike** [comment]
Awesome!

Mike
________________________________
