### ISSUE TITLE
Try to fix belt auto-bridge function introduced in latest DSP update

### ISSUE THREAD

**Issue by soarqin** [Touhma/DSP_Galactic_Scale#205]
Currently auto-bridging would show collide error on planets with large radius.
I've found a simple way to fix it:
While calling `OverlapCapsuleNonAlloc(vec1, vec2, 0.28f, BuildTool._tmp_cols, 425984, QueryTriggerInteraction.Collide));` in function `BuildTool_Path.Physics.CheckBuildConditions()`, reduce 0.28f a bit (tried 0.22f) can resolve this problem.
Might need more tests to see the exact value that works for planets with maximum allowed radius in GalacticScale.

**Comment by innominata** [comment]
I think that this is probably one of those values that needs to be properly mathematically determined, like the spacing for multiplacing inserters on huge planets (which iirc is still broken).
I'll look into it

**Comment by soarqin** [comment]
I don't think this affect much, since all buildings do extra collision checks using PrefabDesc.buildCollider(s).
So this seems only affect belts collision check and reduce it a bit may also make some blueprint working again on large radius planets.

**Comment by innominata** [comment]
Thanks, fixed in 2.11.11 (Hopefully)
