### ISSUE TITLE
cannot set up planet -> planet priority routes

### ISSUE THREAD

**Issue by szhongren** [Touhma/DSP_Galactic_Scale#237]
tried with new game, and existing save.

go to starmap, click on any planet, then on route, then the big + sign

screen flashes for a second and then nothing happens

happy to provide settings or config files if needed, on version 2.16.4

**Comment by innominata** [comment]
has it worked before in GalacticScale? It's not a feature I'm familiar with

**Comment by innominata** [comment]
Fixed in 2.16.5, they added some code to one of the patched functions that I missed, thanks for the report :)

**Comment by innominata** [comment]
https://thunderstore.io/package/download/Galactic_Scale/GalacticScale/2.16.5/
